mapcache:
  image: instedd/planwise-mapserver:mapcache
  # build: .
  # dockerfile: Dockerfile.mapcache
  volumes:
    - "./mapcache.xml:/mapcache/mapcache.xml:ro"
  links:
    - mapserver
  ports:
    - "5002:80"

mapserver:
  image: instedd/planwise-mapserver:mapserver
  # build: .
  # dockerfile: Dockerfile.mapserver
  volumes:
    - "../data:/data:ro"
    - "./mapserver.conf:/etc/apache2/conf-enabled/mapserver.conf:ro"
    - "./planwise.map:/etc/mapserver/planwise.map:ro"
  ports:
    - "5001:80"
