version: '2'

services:
  app:
    image: instedd/planwise:local
    environment:
      DEMO_TILE_URL: "http://mapcache/mapcache/gmaps/kenya@GoogleMapsCompatible/{z}/{x}/{y}.png"
      DATA_PATH: /app/data
      JAR_PATH: /app/lib/planwise-0.5.0-SNAPSHOT-standalone.jar
      DATABASE_URL: "jdbc:postgresql://db/routing?user=planwise&password=planwise"
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: routing
      POSTGRES_HOST: db
      PORT: 3000
    env_file: ".docker-env"

  db:
    image: starefossen/pgrouting:9.4-2.1-2.1
    environment:
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: routing
