db:
  image: starefossen/pgrouting:9.4-2.1-2.1
  environment:
    POSTGRES_PASSWORD: planwise
    POSTGRES_USER: planwise
    POSTGRES_DB: routing

web:
  image: instedd/planwise:latest
  ports:
    - "8080:80"
  links:
    - db
  command: /bin/sh -c "/app/scripts/migrate && java -jar $JAR_PATH"
  environment:
    JAR_PATH: /app/lib/planwise-0.5.0-SNAPSHOT-standalone.jar
    DATABASE_URL: "jdbc:postgresql://db/routing?user=planwise&password=planwise"
    POSTGRES_PASSWORD: planwise
    POSTGRES_USER: planwise
    POSTGRES_DB: routing
    POSTGRES_HOST: db
    PORT: 80

mapcache:
  image: instedd/planwise-mapserver:kenya-mapcache
  links:
    - mapserver
  ports:
    - "5002:80"

mapserver:
  image: instedd/planwise-mapserver:kenya-mapserver
  links:
    - mapserver-data
  ports:
    - "5001:80"
  volumes_from:
    - mapserver-data

mapserver-data:
  image: instedd/planwise-mapserver:kenya-data
  command: /bin/true
