version: '2.0'

services:
  guissodb:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - guissodb:/var/lib/mysql

  guissoweb:
    image: instedd/guisso
    environment:
      DATABASE_URL: 'mysql2://root@guissodb/guisso'
      RAILS_CONFIG__action_mailer__smtp_settings__address: smtp
      RAILS_CONFIG__action_mailer__smtp_settings__port: 25
      RAILS_CONFIG__action_mailer__smtp_settings__authentication: plain
      RAILS_CONFIG__action_mailer__smtp_settings__openssl_verify_mode: none
    volumes:
      - ./telemetry.yml:/app/config/telemetry.yml
    networks:
      default:
        aliases:
          - guisso-local.instedd.org
    depends_on:
      - guissodb

networks:
  default:
    external:
      name: planwise

volumes:
  guissodb:
