version: '2.0'

services:
  resmapdb:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - resmapdb:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:1.7
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - elastic:/usr/share/elasticsearch/data

  redis:
    image: redis

  resmapweb: &rails
    image: instedd/resourcemap:wip
    environment:
      ELASTICSEARCH_URL: 'elasticsearch:9200'
      REDIS_URL: 'redis://redis:6379'
      DATABASE_URL: 'mysql2://root@resmapdb/resourcemap'
      SECRET_KEY_BASE: secret
      GUISSO_ENABLED: 'true'
      GUISSO_URL: http://guisso-local.instedd.org
    env_file:
      - ./guisso.env
    depends_on:
      - resmapdb
      - elasticsearch
      - redis
    volumes:
      - ./google_maps.key:/app/config/google_maps.key
      - ./initial_setup/setup.rake:/app/lib/tasks/setup.rake
      - ./initial_setup/kenya-facilities.csv:/app/lib/tasks/kenya-facilities.csv
    networks:
      default:
        aliases:
          - resmap-local.instedd.org

  resque:
    <<: *rails
    command: rake resque:work TERM_CHILD=1 FORK_PER_JOB=false
    ports: []

  resque_scheduler:
    <<: *rails
    command: rake resque:scheduler
    ports: []

networks:
  default:
    external:
      name: planwise

volumes:
  resmapdb:
  elastic:
  redis:
