version: '2.0'

services:
  planwisedb:
    image: starefossen/pgrouting:9.4-2.1-2.1
    environment:
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: routing
    volumes:
      - planwisedb:/var/lib/postgresql/data

  planwiseweb:
    image: instedd/planwise:feature_integration-tests
    environment:
      DEMO_TILE_URL: "http://mapcache/mapcache/gmaps/kenya@GoogleMapsCompatible/{z}/{x}/{y}.png"
      DATA_PATH: /data
      JAR_PATH: /app/lib/planwise-0.6.0-SNAPSHOT-standalone.jar
      DATABASE_URL: "jdbc:postgresql://planwisedb/routing?user=planwise&password=planwise"
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: routing
      POSTGRES_HOST: planwisedb
      PORT: 80
      CALCULATE_DEMAND: 'false'
      RASTER_ISOCHRONES: 'false'
      GUISSO_URL: http://guisso-local.instedd.org
      RESOURCEMAP_URL: http://resmap-local.instedd.org
    env_file:
      - ./guisso.env
    depends_on:
      - planwisedb
    volumes_from:
      - mapserver-data
    networks:
      default:
        aliases:
          - planwise-local.instedd.org

  mapcache:
    image: instedd/planwise-mapserver:kenya-mapcache
    pid: host

  mapserver:
    image: instedd/planwise-mapserver:kenya-mapserver
    pid: host
    volumes_from:
      - mapserver-data

  mapserver-data:
    image: instedd/planwise-mapserver:kenya-data
    command: /bin/true

networks:
  default:
    external:
      name: planwise

volumes:
  planwisedb:
